---
# specific hosts defined in the inventory file to run this playbook
- hosts: R1
  gather_facts: no
  tasks: 
# using the cisco bgp module to config bgp on each specific router
    - name: configure global bgp as 65000
      cisco.ios.ios_bgp:
        config:
          bgp_as: 65000
          router_id: 1.1.1.1
          log_neighbor_changes: true
          neighbors:
          - neighbor: 10.200.200.2
            remote_as: 65001
          address_family:
          - afi: ipv4
            neighbors:
            - neighbor: 10.200.200.2
              next_hop_self: yes
            redistribute:
            - protocol: ospf
              id: 1
          networks:
          - prefix: 10.0.0.0
            masklen: 8
        operation: merge

- hosts: R2
  gather_facts: no
  tasks: 

    - name: configure global bgp as 65001
      cisco.ios.ios_bgp:
        config:
          bgp_as: 65001
          router_id: 2.2.2.2
          log_neighbor_changes: true
          neighbors:
          - neighbor: 10.200.200.1
            remote_as: 65000
          address_family:
          - afi: ipv4
            neighbors:
            - neighbor: 10.200.200.1
              next_hop_self: yes
            redistribute:
            - protocol: ospf
              id: 1
          networks:
          - prefix: 10.0.0.0
            masklen: 8
        operation: merge
