---

- hosts: localhost
  tasks:
    - debug:
        msg: Test message for myself '{{ hostvars[groups['cisco'][0]].ansible_host }}'

- name: Set Hostnames
  include: hostname.yaml

- name: Set Login Banner
  include: banner.yaml

- name: Set Interfaces
  include: interfaces.yaml

- name: Set NTP
  include: ntp.yaml

- name: Set Nameservers
  include: nameserver.yaml

- name: Set SNMP
  include: snmp.yaml

- name: Set Logging
  include: logging.yaml

- name: Set OSPF
  include: ospf.yaml

- hosts: cisco
  gather_facts: no
  tasks: 
    - name: Write Memory
      cisco.ios.ios_config:
        save_when: modified


