---

- name:  Configure Cisco Switches
  hosts: cisco
  gather_facts: no
  tasks:
    - name: Configure Cisco login banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          Login banner added with ansible!
        state: present

    - name: Configure Cisco name servers
      cisco.ios.ios_system:
        name_servers:
        - 8.8.8.8
        - 8.8.4.4

    - name: Configure Cisco host logging
      cisco.ios.ios_logging:
        dest: host
        name: 192.168.100.128
        state: present
 
    - name: Configure Cisco SNMP 
      cisco.ios.ios_config:
        lines:
          - snmp-server community public RO 
          - snmp-server community private RW 
          - snmp-server trap-source Loopback0
          - snmp-server contact test@fergus.ni
          - snmp-server enable traps ospf state-change
          - snmp-server enable traps ospf errors
          - snmp-server host 192.168.100.128 version 2c public udp-port 161



- name: sw1 tasks
  include: sw1.yaml

- name: sw2 tasks
  include: sw2.yaml

- name: sw2 tasks
  include: hostname.yaml



