---

- name: Configure sw1 IPv4
  hosts: sw1
  gather_facts: no
  tasks:
    - name: Configure sw1 GigabitEthernet2
      cisco.ios.ios_config:
        lines:
        - description test interface
        - ip address 10.10.10.12 255.255.255.0
        parents: interface GigabitEthernet2
    
    - name: Configure sw1 GigabitEthernet3
      cisco.ios.ios_config:
        lines:
        - description test interface
        - ip address 10.10.10.13 255.255.255.0
        parents: interface GigabitEthernet3

- name: Configure sw2 IPv4
  hosts: sw2
  gather_facts: no
  tasks:
    - name: Configure sw2 GigabitEthernet2
      cisco.ios.ios_config:
        lines:
        - description test interface
        - ip address 10.10.10.22 255.255.255.0
        parents: interface GigabitEthernet2
    
    - name: Configure sw2 GigabitEthernet3
      cisco.ios.ios_config:
        lines:
        - description test interface
        - ip address 10.10.10.23 255.255.255.0
        parents: interface GigabitEthernet3
