---

- hosts: cisco
  gather_facts: no
  tasks: 
    - name: Configure Cisco OSPF
      cisco.ios.ios_config:
        lines:
        - network 10.10.10.8 0.0.0.3 area 0
        - network 10.10.10.12 0.0.0.3 area 0
        parents: router ospf 1

