---

- hosts: cisco
  gather_facts: no
  tasks:
    - name: Configure Cisco SNMP 
      cisco.ios.ios_config:
        lines:
          - snmp-server community public RO 
          - snmp-server community private RW 
          - snmp-server trap-source Loopback0
          - snmp-server contact test@fergus.ni
          - snmp-server enable traps ospf state-change
          - snmp-server enable traps ospf errors
          - snmp-server host 192.168.100.128 version 2c public udp-port 161


